#################################
#     Configuration file of     #
# CloudPermissionWhitelist v4.0 #
#################################

# change update check settings
updateCheck:
  check: true
  notifyConsole: true
  notifyPlayer: true

# default /allowtempjoin time
tempJoinTime: 300

# set if the vanilla whitelist should be disabled when the plugin is enabled
autoDisableWhitelist: true

# send a JSON String which contains a random UUID (will change every time) to huddu.io to report usage statistics
statsTracking: true
