main: net.jandie1505.CloudPermissionWhitelist.CloudPermissionWhitelist
name: CloudPermissionWhitelist
version: 3.2
api-version: 1.13
website: jandie1505.net

commands:
  localkick:
    description: Kick a player (to lobby)
    usage: /localkick <Player> [Reason]
    permission: cloudpermissionwhitelist.localkick
  allowtempjoin:
    description: Allows a player to join temporary without the permission
    usage: /allowtempjoin <Player> [Time]
    permission: cloudpermissionwhitelist.allowtempjoin
  denytempjoin:
    description: Removes a player from the temp join list
    usage: /denytempjoin <Player>
    permission: cloudpermissionwhitelist.denytempjoin
  denyalltempjoin:
    description: Deny all temp join allowed players
    usage: /denyalltempjoin
    permission: cloudpermissionwhitelist.denyalltempjoin
  listtempjoin:
    description: List temp join allowed players
    usage: /listtempjoin
    permission: cloudpermissionwhitelist.listtempjoin
  joinprotection:
    description: Manage the join protection
    usage: /joinprotection <status/on/off> [time]
    permission: cloudpermissionwhitelist.joinprotection

permissions:
  cloudpermissionwhitelist.join.*:
    default: false
    description: Allow the join on ALL servers
  cloudpermissionwhitelist.join.<TaskName>:
    default: false
    description: Allow the join on <TaskName>
  cloudpermissionwhitelist.localkick:
    default: op
    description: Allows to use the /localkick command
  cloudpermissionwhitelist.allowtempjoin:
    default: op
    description: Allows to use the /allowtempjoin command
  cloudpermissionwhitelist.denytempjoin:
    default: op
    description: Allows to use the /denytempjoin command
  cloudpermissionwhitelist.listtempjoin:
    default: op
    description: Allows to use the /listtempjoin command
  cloudpermissionwhitelist.joinprotection:
    default: op
    description: Allows to use the /joinprotection command
  cloudpermissionwhitelist.updatenotify:
    default: op
    description: Receive update notifications when enabled
  cloudpermissionwhitelist.*:
    default: op
    description: Wildcard permission
    children:
      cloudpermissionwhitelist.join.*: true
      cloudpermissionwhitelist.localkick: true
      cloudpermissionwhitelist.allowtempjoin: true
      cloudpermissionwhitelist.denytempjoin: true
      cloudpermissionwhitelist.listtempjoin: true
      cloudpermissionwhitelist.joinprotection: true
      cloudpermissionwhitelist.updatenotify: true
